[registries.crates-io]
# The sparse protocol is currently planned to become the default for crates.io in the 1.70.0 release in a few months.
protocol = "sparse"

[alias]
format = "fmt --all"
format-check = "fmt --all -- --check"
lint = "clippy --all-targets --all-features -- -D warnings"
lint-fix = "clippy --all-targets --all-features --fix --allow-dirty --allow-staged"
coverage = "llvm-cov --no-clean --lcov --output-path coverage.lcov"
